name: PHP CI
on: 
  - push
  - pull_request
jobs:
  builds:

    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress 
      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}