name: PHP CI
on: 
  - push
  - pull_request
jobs:
  builds:

    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test